### PR TITLE
Island data

### PR DESCRIPTION
**Pull request by kaydeethree**
Name/link a few fields

### CODE REVIEW

**Comment by kaydeethree** [comment]
One link I can't figure out how to make is that MJIGatheringItem#2 is MJIKeyItem#1 (what I've called "Sort" in this PR)

**Comment by Supamiu** [comment]
Hi, thanks for your contribution 🙂 

I'm not sure I understand what you mean by "MJIGatheringItem#2 is MJIKeyItem#1", can you explain a bit more with example screenshots if possible?

**Comment by kaydeethree** [comment]
Please disregard the initial comment. With the current PR state, this is what MJIGatheringItem looks like. image

This is despite that fact that MJIGatheringTool looks like this: 
image

**Comment by Supamiu** [comment]
I see, this is just because Saint doesn't find how to represent this by string so it just puts a link like what you're seeing. I assume because it's too deep (to get the string, you'd have to read the MJIGatheringTool row, then read the associated Item row, then grab the string in the Name column).

If you're willing to use this data, I highly suggest using either SaintCoinach directly (as a .Net dependency) or Lumina (same, available in NuGet iirc). Or parsing the CSV to resolve the link by yourself.

Anyways, adding defaultColumn set to

**Comment by kaydeethree** [comment]
Oh I'm already parsing the CSVs. Just trying to contribute my knowledge back to the community.

Your comment cut off. What's defaultColumn?

**Comment by Supamiu** [comment]
Oh I just forgot to remove that line, defaultColumn is already set for MJIGatheringTool

**Comment by kaydeethree** [comment]
Alright. Any other changes needed to pass review / merge?

**Comment by Supamiu** [comment]
I think we're good to go 🙂

**Review by Supamiu — APPROVED** [review]

**Pull request merged**
