### PR TITLE
Add missing Z in SubmarineExploration coordinates

### PR DESCRIPTION
**Pull request by shambarick**

### CODE REVIEW

**Comment by IcarusTwine** [comment]
Is there anything specific why you thought this might be Z on a 2d map ?

**Comment by IcarusTwine** [comment]
> Is there anything specific why you thought this might be Z on a 2d map ?

I only ask because I don't do much subs so not sure, as far as I know it's a 2d map anyway

**Comment by shambarick** [comment]
They went with X,Y,Z for Submarines. The distances between some sectors that may look the same if you only look at them in a 2D pov, aren't. The reason behind that is because of the Z axis, it takes into account the depth. It only applies to submarines. Airship sectors are in a 2D plan, so only X and Y axises.

I use them to compute the estimated time for a trip on mogship.com

If you wanna know more about it, lmk

**Comment by wolfcomp** [comment]
@IcarusTwine they actually use a 3d map coord system in the time calculation *from what I can decode alone* and this is what I have figured out so far

`TimeToBeDone = 720 + Duration<min> + round((sqrt((x1 - x2) ^ 2 + (y1 - y2)^2 + (z1 - z2)^2) * (j / s)) * 1440)`
s = speed of the airship or submarine
j = 0.04143 for airships (59m40s)
j = 0.02765 for submarines (39m49s)
NOTE: this is only an approximation of the time used, as it can deviate from what the game shows.

**Comment by ayyaruq** [comment]
This does look correct for the Z reference @IcarusTwine.

**Comment by IcarusTwine** [comment]
Perfect ! Thank you for the explanation and great find!

**Comment by shambarick** [comment]
That's almost correct but it's missing a few things.

Each map has a starting sector (airship and submarine).
Airship:  sectors #127
Submarine: sectors #0 (Deep sea site), #31 (Sea of ash), #52 (Sea of jade)

The correct way to get the time is as following:
Trip is A -> B -> C
A: The starting sector of the map, the game doesn't show it
B: The first sector you select
C: The second sector you select

TotalDistance = range A->B + range B->C + distance A->B + distance B->C + timeForSurvey B + timeForSurvey C + rangeForSurvey B + rangeForSurvey C

timeForSurvey = Duration< min > * 70
rangeForSurvey = DistanceForSurvey

distance A->B = floor(sqrt((x1 - x2)^2 + (y1 - y2)^2 + (z1 - z2)^2) * n)
n = 60 (airship)
n = 39.9 (submarine)

range A->B = floor(sqrt((x1 - x2)^2 + (y1 - y2)^2 + (z1 - z2)^2) / n)
n = 19.2265 (airship)
n = 28.5716 (submarine)


days = ((TotalDistance  / speed) / 1440) + 0.5;
hours = ((TotalDistance  / speed) / 60 + 12) % 24;
minutes = (TotalDistance  / speed) % 60;

**Comment by wolfcomp** [comment]
Didn't have time to comment on this, but some few days after the previous comment me and some other people dug through the in-game code to figure out how the calculation was actually done, [documented here.](https://docs.google.com/document/d/1Fl5X16oPF-4X29v5PukCkVgcPhZsbzhKcoq6Us7fhKU/edit#heading=h.moh1odgc2k82) It's somewhat a weird set of values, but this is actually how things are done through the game.

**Pull request merged**
